import { Producer } from '@/types/producer';
import { EventItem } from '@/types/event';
import { EventWalletPosition, FinancialLedgerEntry, PayoutRequest, AdvanceRequest } from '@/types/finance';
import { CommercialClient, CommercialOpportunity, CommercialProposal } from '@/types/commercial';
import {
  MarketingCampaign,
  ReadyCampaignTemplate,
  ReadyCampaignInstance,
  AdRealStatusItem,
  Ga4EventLog,
  TikTokTransmissionLog,
  UtmLinkItem,
  WhatsAppTemplate,
  EmailTemplate,
  AutomationJourney,
} from '@/types/marketing';
import { AbandonedCart, RecoveryOpportunity, PaymentRecoveryItem } from '@/types/remarketing';

export const mockProducer: Producer = {
  id: 'prod-01',
  name: 'ABC Produções & Eventos Ltda',
  tradeName: 'ABC Produções',
  cnpj: '12.345.678/0001-90',
  code: 'PROD-001',
  status: 'ACTIVE',
  email: 'financeiro@abcproducoes.com.br',
  phone: '(41) 3322-8800',
  bankName: 'Itaú Unibanco S.A. (341)',
  agency: '0422',
  account: '88120-1',
  pixKey: 'financeiro@abcproducoes.com.br',
  kpis: {
    saldoTotal: 820450.0,
    disponivel: 570450.0,
    aReceber: 200000.0,
    emAntecipacao: 100000.0,
    emRepasse: 150000.0,
    despesas: 80000.0,
    bloqueado: 100000.0,
    projetado: 1240000.0,
  },
};

export const mockEvents: EventItem[] = [
  {
    id: 'ev-101',
    name: 'Festival XYZ 2026',
    code: 'EVT-101',
    venue: 'Pedreira Paulo Leminski',
    city: 'Curitiba',
    state: 'PR',
    dateStart: '10/10/2026',
    dateEnd: '12/10/2026',
    time: '18:00',
    imageUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=1200&q=80',
    status: 'ACTIVE',
    producerId: 'prod-01',
    producerName: 'ABC Produções & Eventos Ltda',

    grossSales: 500000.0,
    ticketsSold: 3250,
    totalCapacity: 5000,
    ticketsAvailable: 1750,
    courtesiesCount: 120,
    occupationRate: 65.0,

    averageTicket: 153.84,
    breakEvenTarget: 320000.0,
    breakEvenAchievedRate: 156.2, // 156% of break-even achieved
    salesGoalAmount: 700000.0,
    salesGoalAchievedRate: 71.4,
    projectedGrossSales: 680000.0,
    salesVelocityPerHour: 18.5,

    paymentMethods: [
      { method: 'PIX', label: 'PIX Instantâneo', amount: 260000.0, count: 1690, percentage: 52.0, color: '#10b981' },
      { method: 'CREDIT_CARD', label: 'Cartão de Crédito à Vista', amount: 150000.0, count: 975, percentage: 30.0, color: '#3b82f6' },
      { method: 'CREDIT_INSTALLMENTS', label: 'Cartão Parcelado (até 12x)', amount: 75000.0, count: 488, percentage: 15.0, color: '#8b5cf6' },
      { method: 'BOLETO', label: 'Boleto Bancário', amount: 15000.0, count: 97, percentage: 3.0, color: '#f59e0b' },
    ],

    sectors: [
      {
        id: 'sec-1',
        name: 'Pista Premium VIP',
        totalCapacity: 1500,
        soldCount: 1250,
        availableCount: 250,
        color: '#6366f1',
        batches: [
          { id: 'b-1', name: 'Lote 1', price: 220, totalQuantity: 800, soldQuantity: 800, availableQuantity: 0, status: 'SOLD_OUT' },
          { id: 'b-2', name: 'Lote 2', price: 260, totalQuantity: 700, soldQuantity: 450, availableQuantity: 250, status: 'ACTIVE' },
        ],
      },
      {
        id: 'sec-2',
        name: 'Camarote Open Bar',
        totalCapacity: 800,
        soldCount: 680,
        availableCount: 120,
        color: '#ec4899',
        batches: [
          { id: 'b-3', name: 'Lote Promocional', price: 350, totalQuantity: 400, soldQuantity: 400, availableQuantity: 0, status: 'SOLD_OUT' },
          { id: 'b-4', name: 'Lote 2', price: 420, totalQuantity: 400, soldQuantity: 280, availableQuantity: 120, status: 'ACTIVE' },
        ],
      },
      {
        id: 'sec-3',
        name: 'Pista Geral',
        totalCapacity: 2700,
        soldCount: 1320,
        availableCount: 1380,
        color: '#14b8a6',
        batches: [
          { id: 'b-5', name: 'Lote 1 Meia/Solidário', price: 90, totalQuantity: 1500, soldQuantity: 1320, availableQuantity: 180, status: 'ACTIVE' },
          { id: 'b-6', name: 'Lote 2 Inteira', price: 180, totalQuantity: 1200, soldQuantity: 0, availableQuantity: 1200, status: 'PENDING' },
        ],
      },
    ],

    timeline: [
      { date: '2026-10-01', label: '01 Out', dailyAmount: 85000, accumulatedAmount: 85000, ticketsSold: 550 },
      { date: '2026-10-02', label: '02 Out', dailyAmount: 65000, accumulatedAmount: 150000, ticketsSold: 420 },
      { date: '2026-10-03', label: '03 Out', dailyAmount: 52000, accumulatedAmount: 202000, ticketsSold: 335 },
      { date: '2026-10-04', label: '04 Out', dailyAmount: 48000, accumulatedAmount: 250000, ticketsSold: 310 },
      { date: '2026-10-05', label: '05 Out', dailyAmount: 62000, accumulatedAmount: 312000, ticketsSold: 405 },
      { date: '2026-10-06', label: '06 Out', dailyAmount: 78000, accumulatedAmount: 390000, ticketsSold: 510 },
      { date: '2026-10-07', label: '07 Out', dailyAmount: 55000, accumulatedAmount: 445000, ticketsSold: 360 },
      { date: '2026-10-08', label: '08 Out', dailyAmount: 35000, accumulatedAmount: 480000, ticketsSold: 230 },
      { date: '2026-10-09', label: '09 Out', dailyAmount: 20000, accumulatedAmount: 500000, ticketsSold: 130 },
    ],

    recentOrders: [
      { id: 'ord-901', orderNumber: '#DI-88492', customerName: 'Mariana Duarte Souza', customerEmail: 'mariana.souza@gmail.com', itemsCount: 2, totalAmount: 440.0, paymentMethod: 'PIX', status: 'APPROVED', createdAt: '2026-10-09T12:45:00', sectorName: 'Pista Premium VIP' },
      { id: 'ord-902', orderNumber: '#DI-88491', customerName: 'Rodrigo Albuquerque', customerEmail: 'rodrigo.alb@uol.com.br', itemsCount: 1, totalAmount: 420.0, paymentMethod: 'Cartão de Crédito', status: 'APPROVED', createdAt: '2026-10-09T11:30:00', sectorName: 'Camarote Open Bar' },
      { id: 'ord-903', orderNumber: '#DI-88490', customerName: 'Camila Fernandes', customerEmail: 'camilaf@outlook.com', itemsCount: 4, totalAmount: 360.0, paymentMethod: 'PIX', status: 'APPROVED', createdAt: '2026-10-09T10:14:00', sectorName: 'Pista Geral' },
      { id: 'ord-904', orderNumber: '#DI-88489', customerName: 'Lucas Zanetti', customerEmail: 'l.zanetti@empresa.com.br', itemsCount: 2, totalAmount: 520.0, paymentMethod: 'Cartão Parcelado', status: 'APPROVED', createdAt: '2026-10-09T09:20:00', sectorName: 'Pista Premium VIP' },
    ],
  },
  {
    id: 'ev-102',
    name: 'Show Nacional ABC 2026',
    code: 'EVT-102',
    venue: 'Live Curitiba',
    city: 'Curitiba',
    state: 'PR',
    dateStart: '24/10/2026',
    time: '21:00',
    imageUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80',
    status: 'ACTIVE',
    producerId: 'prod-01',
    producerName: 'ABC Produções & Eventos Ltda',

    grossSales: 280000.0,
    ticketsSold: 1800,
    totalCapacity: 2000,
    ticketsAvailable: 200,
    courtesiesCount: 50,
    occupationRate: 90.0,

    averageTicket: 155.55,
    breakEvenTarget: 180000.0,
    breakEvenAchievedRate: 155.5,
    salesGoalAmount: 300000.0,
    salesGoalAchievedRate: 93.3,
    projectedGrossSales: 310000.0,
    salesVelocityPerHour: 8.2,

    paymentMethods: [
      { method: 'PIX', label: 'PIX Instantâneo', amount: 168000.0, count: 1080, percentage: 60.0, color: '#10b981' },
      { method: 'CREDIT_CARD', label: 'Cartão de Crédito à Vista', amount: 84000.0, count: 540, percentage: 30.0, color: '#3b82f6' },
      { method: 'CREDIT_INSTALLMENTS', label: 'Cartão Parcelado', amount: 28000.0, count: 180, percentage: 10.0, color: '#8b5cf6' },
    ],
    sectors: [],
    timeline: [],
    recentOrders: [],
  },
  {
    id: 'ev-103',
    name: 'Grande Teatro Clássico 2026',
    code: 'EVT-103',
    venue: 'Teatro Positivo',
    city: 'Curitiba',
    state: 'PR',
    dateStart: '05/11/2026',
    time: '20:30',
    imageUrl: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=1200&q=80',
    status: 'ACTIVE',
    producerId: 'prod-01',
    producerName: 'ABC Produções & Eventos Ltda',

    grossSales: 150000.0,
    ticketsSold: 950,
    totalCapacity: 2000,
    ticketsAvailable: 1050,
    courtesiesCount: 40,
    occupationRate: 47.5,

    averageTicket: 157.89,
    breakEvenTarget: 120000.0,
    breakEvenAchievedRate: 125.0,
    salesGoalAmount: 250000.0,
    salesGoalAchievedRate: 60.0,
    projectedGrossSales: 220000.0,
    salesVelocityPerHour: 4.1,

    paymentMethods: [
      { method: 'PIX', label: 'PIX Instantâneo', amount: 75000.0, count: 475, percentage: 50.0, color: '#10b981' },
      { method: 'CREDIT_CARD', label: 'Cartão de Crédito', amount: 60000.0, count: 380, percentage: 40.0, color: '#3b82f6' },
      { method: 'BOLETO', label: 'Boleto Bancário', amount: 15000.0, count: 95, percentage: 10.0, color: '#f59e0b' },
    ],
    sectors: [],
    timeline: [],
    recentOrders: [],
  },
  {
    id: 'ev-104',
    name: 'Eletrônica Sessions Sunset',
    code: 'EVT-104',
    venue: 'Ópera de Arame',
    city: 'Curitiba',
    state: 'PR',
    dateStart: '18/11/2026',
    time: '16:00',
    imageUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1200&q=80',
    status: 'UPCOMING',
    producerId: 'prod-01',
    producerName: 'ABC Produções & Eventos Ltda',

    grossSales: 380000.0,
    ticketsSold: 2100,
    totalCapacity: 2500,
    ticketsAvailable: 400,
    courtesiesCount: 80,
    occupationRate: 84.0,

    averageTicket: 180.95,
    breakEvenTarget: 240000.0,
    breakEvenAchievedRate: 158.3,
    salesGoalAmount: 450000.0,
    salesGoalAchievedRate: 84.4,
    projectedGrossSales: 450000.0,
    salesVelocityPerHour: 12.0,

    paymentMethods: [
      { method: 'PIX', label: 'PIX Instantâneo', amount: 228000.0, count: 1260, percentage: 60.0, color: '#10b981' },
      { method: 'CREDIT_CARD', label: 'Cartão de Crédito', amount: 152000.0, count: 840, percentage: 40.0, color: '#3b82f6' },
    ],
    sectors: [],
    timeline: [],
    recentOrders: [],
  },
  {
    id: 'ev-105',
    name: 'Disk Stand-Up Fest',
    code: 'EVT-105',
    venue: 'Teatro Fernanda Montenegro',
    city: 'Curitiba',
    state: 'PR',
    dateStart: '01/09/2026',
    time: '20:00',
    imageUrl: 'https://images.unsplash.com/photo-1585699324551-f6c309eedeca?auto=format&fit=crop&w=1200&q=80',
    status: 'COMPLETED',
    producerId: 'prod-01',
    producerName: 'ABC Produções & Eventos Ltda',

    grossSales: 90000.0,
    ticketsSold: 750,
    totalCapacity: 750,
    ticketsAvailable: 0,
    courtesiesCount: 25,
    occupationRate: 100.0,

    averageTicket: 120.0,
    breakEvenTarget: 50000.0,
    breakEvenAchievedRate: 180.0,
    salesGoalAmount: 90000.0,
    salesGoalAchievedRate: 100.0,
    projectedGrossSales: 90000.0,
    salesVelocityPerHour: 0.0,

    paymentMethods: [
      { method: 'PIX', label: 'PIX Instantâneo', amount: 54000.0, count: 450, percentage: 60.0, color: '#10b981' },
      { method: 'CREDIT_CARD', label: 'Cartão de Crédito', amount: 36000.0, count: 300, percentage: 40.0, color: '#3b82f6' },
    ],
    sectors: [],
    timeline: [],
    recentOrders: [],
  },
];

export const mockWallets: EventWalletPosition[] = [
  {
    id: 'w-101',
    eventId: 'ev-101',
    eventName: 'Festival XYZ 2026',
    producerId: 'prod-01',
    producerName: 'ABC Produções & Eventos Ltda',
    venue: 'Pedreira Paulo Leminski',
    date: '10/10/2026 a 12/10/2026',
    grossTicketSales: 500000.0,
    diskFeeTotal: 50000.0, // 10%
    spreadFeeTotal: 12500.0, // 2.5%
    advanceFeeTotal: 7500.0,
    otherFeesTotal: 2000.0,
    expensesTotal: 100000.0,
    repaymentsPaidTotal: 100000.0,
    repaymentsScheduledTotal: 30000.0,
    balanceAvailable: 148000.0,
    blockedBalance: 0.0,
    projectedBalance: 680000.0,
    advancesPaidTotal: 50000.0,
    contingencyReserveAmount: 50000.0,
    obligationsReservedTotal: 30000.0,
    obligationsPaidTotal: 20000.0,
    refundsPaidTotal: 0.0,
    isCancellationBlocked: false,
    status: 'OPEN',
  },
  {
    id: 'w-102',
    eventId: 'ev-102',
    eventName: 'Show Nacional ABC 2026',
    producerId: 'prod-01',
    producerName: 'ABC Produções & Eventos Ltda',
    venue: 'Live Curitiba',
    date: '24/10/2026',
    grossTicketSales: 280000.0,
    diskFeeTotal: 22400.0, // 8%
    spreadFeeTotal: 8400.0,
    advanceFeeTotal: 0.0,
    otherFeesTotal: 0.0,
    expensesTotal: 59200.0,
    repaymentsPaidTotal: 0.0,
    repaymentsScheduledTotal: 0.0,
    balanceAvailable: 190000.0,
    blockedBalance: 0.0,
    projectedBalance: 340000.0,
    advancesPaidTotal: 0.0,
    contingencyReserveAmount: 25000.0,
    obligationsReservedTotal: 15000.0,
    obligationsPaidTotal: 0.0,
    refundsPaidTotal: 0.0,
    isCancellationBlocked: false,
    status: 'OPEN',
  },
  {
    id: 'w-103',
    eventId: 'ev-103',
    eventName: 'Grande Teatro Clássico 2026',
    producerId: 'prod-01',
    producerName: 'ABC Produções & Eventos Ltda',
    venue: 'Teatro Positivo',
    date: '05/11/2026',
    grossTicketSales: 150000.0,
    diskFeeTotal: 15000.0,
    spreadFeeTotal: 4500.0,
    advanceFeeTotal: 0.0,
    otherFeesTotal: 0.0,
    expensesTotal: 20500.0,
    repaymentsPaidTotal: 0.0,
    repaymentsScheduledTotal: 0.0,
    balanceAvailable: 110000.0,
    blockedBalance: 0.0,
    projectedBalance: 220000.0,
    advancesPaidTotal: 0.0,
    contingencyReserveAmount: 15000.0,
    obligationsReservedTotal: 10000.0,
    obligationsPaidTotal: 0.0,
    refundsPaidTotal: 0.0,
    isCancellationBlocked: false,
    status: 'OPEN',
  },
];

export const mockLedgerEntries: FinancialLedgerEntry[] = [
  {
    id: 'led-1',
    producerId: 'prod-01',
    eventWalletId: 'w-101',
    eventName: 'Festival XYZ 2026',
    orderNumber: '#DI-88492',
    entryType: 'VENDA_INGRESSO',
    direction: 'CREDIT',
    amount: 440.0,
    balanceAfter: 148000.0,
    description: 'Venda aprovada Pedido #DI-88492 (2 ingressos Pista Premium)',
    isReversed: false,
    createdAt: '2026-10-09T12:45:00',
  },
  {
    id: 'led-2',
    producerId: 'prod-01',
    eventWalletId: 'w-101',
    eventName: 'Festival XYZ 2026',
    orderNumber: '#DI-88492',
    entryType: 'TAXA_SERVICO_DISK',
    direction: 'DEBIT',
    amount: 44.0,
    balanceAfter: 147956.0,
    description: 'Taxa DiskIngressos (10%) retida sobre Pedido #DI-88492',
    isReversed: false,
    createdAt: '2026-10-09T12:45:01',
  },
  {
    id: 'led-3',
    producerId: 'prod-01',
    eventWalletId: 'w-101',
    eventName: 'Festival XYZ 2026',
    entryType: 'REPASSE_PRODUTOR',
    direction: 'DEBIT',
    amount: 100000.0,
    balanceAfter: 148000.0,
    description: 'Execução de Repasse Programado #REP-2026-089 via PIX',
    referenceId: 'REP-2026-089',
    isReversed: false,
    createdAt: '2026-10-05T14:30:00',
  },
  {
    id: 'led-4',
    producerId: 'prod-01',
    eventWalletId: 'w-101',
    eventName: 'Festival XYZ 2026',
    entryType: 'DESPESA_OPERACIONAL',
    direction: 'DEBIT',
    amount: 30000.0,
    balanceAfter: 248000.0,
    description: 'Pagamento GuardSeg Ltda - Segurança e Portaria autorizada NF-4921',
    referenceId: 'EXP-1',
    isReversed: false,
    createdAt: '2026-10-03T10:15:00',
  },
  {
    id: 'led-5',
    producerId: 'prod-01',
    eventWalletId: 'w-101',
    eventName: 'Festival XYZ 2026',
    entryType: 'ANTECIPACAO_PRODUTOR',
    direction: 'DEBIT',
    amount: 50000.0,
    balanceAfter: 278000.0,
    description: 'Liquidação de Operação de Antecipação #ANT-2026-012',
    referenceId: 'ANT-2026-012',
    isReversed: false,
    createdAt: '2026-09-28T16:00:00',
  },
];

export const mockPayoutRequests: PayoutRequest[] = [
  {
    id: 'rep-1',
    scheduleNumber: 'REP-2026-101',
    eventId: 'ev-101',
    eventName: 'Festival XYZ 2026',
    producerId: 'prod-01',
    producerName: 'ABC Produções & Eventos Ltda',
    amount: 30000.0,
    status: 'SCHEDULED',
    paymentMethod: 'PIX',
    destinationBank: 'Itaú Unibanco S.A. (341)',
    destinationPixKey: 'financeiro@abcproducoes.com.br',
    requestedAt: '2026-10-08T15:20:00',
    scheduledDate: '2026-10-15',
    notes: 'Repasse parcelar do marco de 50% de vendas atingido.',
  },
  {
    id: 'rep-2',
    scheduleNumber: 'REP-2026-089',
    eventId: 'ev-101',
    eventName: 'Festival XYZ 2026',
    producerId: 'prod-01',
    producerName: 'ABC Produções & Eventos Ltda',
    amount: 100000.0,
    status: 'PAID',
    paymentMethod: 'PIX',
    destinationBank: 'Itaú Unibanco S.A. (341)',
    destinationPixKey: 'financeiro@abcproducoes.com.br',
    requestedAt: '2026-10-02T10:00:00',
    scheduledDate: '2026-10-05',
    authorizedBy: 'Diretoria Financeira Disk',
    paidAt: '2026-10-05T14:30:00',
    transactionHash: 'pix_e2e_8492048204892019482019',
    notes: 'Primeira parcela contratual de liberação antecipada.',
  },
];

export const mockAdvanceRequests: AdvanceRequest[] = [
  {
    id: 'adv-1',
    advanceNumber: 'ANT-2026-012',
    eventId: 'ev-101',
    eventName: 'Festival XYZ 2026',
    producerId: 'prod-01',
    requestedAmount: 50000.0,
    advanceFeeRate: 2.5,
    advanceFeeCost: 1250.0,
    netAmount: 48750.0,
    status: 'PAID',
    requestedDate: '2026-09-25T11:00:00',
    dueDate: '2026-10-10',
    authorizedBy: 'Carlos Eduardo (Comitê de Crédito Disk)',
    paidAt: '2026-09-28T16:00:00',
  },
];

export const mockCommercialClients: CommercialClient[] = [
  {
    id: 'cli-1',
    name: 'Grupo Renault do Brasil',
    tradeName: 'Renault Brasil',
    document: '02.456.789/0001-20',
    contactName: 'Fernanda Meirelles (RH & Endomarketing)',
    email: 'f.meirelles@renault.com.br',
    phone: '(41) 3380-2000',
    city: 'São José dos Pinhais / PR',
    category: 'EMPRESA',
    totalOrders: 4,
    totalVolume: 84000.0,
    lastPurchaseDate: '2026-10-04',
  },
  {
    id: 'cli-2',
    name: 'Associação dos Magistrados do Paraná',
    tradeName: 'AMAPAR',
    document: '76.123.456/0001-88',
    contactName: 'Dra. Cláudia Silveira',
    email: 'convenios@amapar.org.br',
    phone: '(41) 3017-1000',
    city: 'Curitiba / PR',
    category: 'GRUPO',
    totalOrders: 6,
    totalVolume: 52000.0,
    lastPurchaseDate: '2026-09-22',
  },
  {
    id: 'cli-3',
    name: 'Universidade Positivo / Cruzeiro do Sul',
    tradeName: 'UP Campus Ecoville',
    document: '01.998.776/0001-33',
    contactName: 'Prof. Lucas Guimarães (Diretório Acadêmico)',
    email: 'lucas.da@up.edu.br',
    phone: '(41) 3317-3000',
    city: 'Curitiba / PR',
    category: 'UNIVERSIDADE',
    totalOrders: 3,
    totalVolume: 42000.0,
    lastPurchaseDate: '2026-10-01',
  },
];

export const mockCommercialOpportunities: CommercialOpportunity[] = [
  {
    id: 'opp-1',
    title: 'Lote Corporativo 250 Ingressos Festival XYZ',
    clientName: 'Grupo Renault do Brasil',
    eventId: 'ev-101',
    eventName: 'Festival XYZ 2026',
    stage: 'NEGOCIACAO',
    estimatedValue: 45000.0,
    ticketsQuantity: 250,
    assignedTo: 'Bruno Valente',
    probability: 80,
    closeDate: '2026-10-10',
  },
  {
    id: 'opp-2',
    title: 'Convênio Exclusivo Servidores AMAPAR',
    clientName: 'Associação dos Magistrados do Paraná',
    eventId: 'ev-101',
    eventName: 'Festival XYZ 2026',
    stage: 'PROPOSTA_ENVIADA',
    estimatedValue: 32000.0,
    ticketsQuantity: 150,
    assignedTo: 'Ana Paula Dias',
    probability: 60,
    closeDate: '2026-10-11',
  },
  {
    id: 'opp-3',
    title: 'Camarote Exclusivo Show ABC',
    clientName: 'Rede de Hotéis Slaviero',
    eventId: 'ev-102',
    eventName: 'Show Nacional ABC 2026',
    stage: 'FECHADO_GANHO',
    estimatedValue: 28000.0,
    ticketsQuantity: 80,
    assignedTo: 'Bruno Valente',
    probability: 100,
    closeDate: '2026-10-06',
  },
];

export const mockCommercialProposals: CommercialProposal[] = [
  {
    id: 'prop-1',
    proposalNumber: 'PROP-2026-081',
    clientName: 'Grupo Renault do Brasil',
    eventId: 'ev-101',
    eventName: 'Festival XYZ 2026',
    totalTickets: 250,
    totalAmount: 45000.0,
    discountRate: 15.0,
    status: 'ENVIADA',
    validUntil: '2026-10-10',
    createdAt: '2026-10-05',
  },
  {
    id: 'prop-2',
    proposalNumber: 'PROP-2026-077',
    clientName: 'Rede de Hotéis Slaviero',
    eventId: 'ev-102',
    eventName: 'Show Nacional ABC 2026',
    totalTickets: 80,
    totalAmount: 28000.0,
    discountRate: 10.0,
    status: 'APROVADA',
    validUntil: '2026-10-08',
    createdAt: '2026-10-01',
  },
];

export const mockMarketingCampaigns: MarketingCampaign[] = [
  {
    id: 'camp-1',
    name: 'Meta Ads — Virada de Lote Festival XYZ',
    eventId: 'ev-101',
    eventName: 'Festival XYZ 2026',
    channel: 'META_ADS',
    status: 'ACTIVE',
    budgetSpent: 8500.0,
    impressions: 420000,
    clicks: 14500,
    ctr: 3.45,
    conversions: 620,
    attributedRevenue: 136400.0,
    roas: 16.04,
    startDate: '2026-10-01',
    endDate: '2026-10-10',
  },
  {
    id: 'camp-2',
    name: 'Google Ads Search — Ingressos Curitiba Show',
    eventId: 'ev-101',
    eventName: 'Festival XYZ 2026',
    channel: 'GOOGLE_ADS',
    status: 'ACTIVE',
    budgetSpent: 4200.0,
    impressions: 110000,
    clicks: 8900,
    ctr: 8.09,
    conversions: 380,
    attributedRevenue: 83600.0,
    roas: 19.9,
    startDate: '2026-10-02',
  },
  {
    id: 'camp-3',
    name: 'TikTok Ads — Line-up Viral & DJs',
    eventId: 'ev-104',
    eventName: 'Eletrônica Sessions Sunset',
    channel: 'TIKTOK_ADS',
    status: 'ACTIVE',
    budgetSpent: 3000.0,
    impressions: 650000,
    clicks: 18200,
    ctr: 2.8,
    conversions: 240,
    attributedRevenue: 43420.0,
    roas: 14.47,
    startDate: '2026-10-04',
  },
];

export const mockAbandonedCarts: AbandonedCart[] = [
  {
    id: 'cart-1',
    customerName: 'Renata Albuquerque',
    customerEmail: 'renata.alb@gmail.com',
    customerPhone: '(41) 99881-2233',
    eventId: 'ev-101',
    eventName: 'Festival XYZ 2026',
    sectorName: 'Pista Premium VIP',
    ticketsCount: 2,
    cartValue: 440.0,
    abandonedAt: '2026-10-09T11:45:00',
    recoveryStatus: 'RECOVERY_SENT',
    channelSent: 'WHATSAPP',
  },
  {
    id: 'cart-2',
    customerName: 'Felipe Goulart',
    customerEmail: 'fgoulart@hotmail.com',
    customerPhone: '(41) 98776-5544',
    eventId: 'ev-101',
    eventName: 'Festival XYZ 2026',
    sectorName: 'Camarote Open Bar',
    ticketsCount: 2,
    cartValue: 840.0,
    abandonedAt: '2026-10-09T10:10:00',
    recoveryStatus: 'PENDING',
  },
  {
    id: 'cart-3',
    customerName: 'Carla Nogueira',
    customerEmail: 'carla.nog@gmail.com',
    customerPhone: '(41) 99123-4567',
    eventId: 'ev-102',
    eventName: 'Show Nacional ABC 2026',
    sectorName: 'Pista Padrão',
    ticketsCount: 1,
    cartValue: 155.0,
    abandonedAt: '2026-10-09T08:20:00',
    recoveryStatus: 'RECOVERED',
    channelSent: 'EMAIL',
  },
];

// 8 Modelos de Campanhas Prontas do Vídeo (Seção D da especificação)
export const mockReadyCampaignTemplates: ReadyCampaignTemplate[] = [
  {
    id: 'rc-1',
    title: 'Acelerar Vendas',
    slug: 'acelerar-vendas',
    tagline: 'Promoção de Curta Duração',
    description: 'Campanha de tiro curto para aquecimento rápido de bilheteria com gatilhos de urgência.',
    channels: ['WHATSAPP', 'INSTAGRAM', 'EMAIL'],
    targetAudience: 'Compradores recentes da DiskIngressos + Leads quentes cadastrados',
    suggestedBudgetMin: 500,
    suggestedBudgetMax: 1500,
    expectedDurationDays: 3,
    category: 'CONVERSAO',
  },
  {
    id: 'rc-2',
    title: 'Lançamento do Evento',
    slug: 'lancamento-evento',
    tagline: 'Estratégia Multicanal de Abertura',
    description: 'Mobilização massiva de primeiro lote em todos os canais digitais simultaneamente.',
    channels: ['INSTAGRAM', 'GOOGLE_ADS', 'TIKTOK', 'WHATSAPP', 'EMAIL', 'AFILIADOS'],
    targetAudience: 'Base total de fãs, seguidores, lookalike 1% e interesse musical segmentado',
    suggestedBudgetMin: 2000,
    suggestedBudgetMax: 6000,
    expectedDurationDays: 7,
    category: 'LANCAMENTO',
  },
  {
    id: 'rc-3',
    title: 'Virada de Lote',
    slug: 'virada-de-lote',
    tagline: 'Gatilho de Urgência & Escassez',
    description: 'Anúncios de contagem regressiva avisando aumento de preço em 48h.',
    channels: ['INSTAGRAM', 'WHATSAPP', 'EMAIL'],
    targetAudience: 'Visitantes dos últimos 14 dias + Carrinhos abandonados não convertidos',
    suggestedBudgetMin: 800,
    suggestedBudgetMax: 2500,
    expectedDurationDays: 2,
    category: 'CONVERSAO',
  },
  {
    id: 'rc-4',
    title: 'Últimas Vagas',
    slug: 'ultimas-vagas',
    tagline: 'Reta Final / Sold-Out',
    description: 'Comunicação de alta intensidade para esgotar os últimos 10% dos setores nobres.',
    channels: ['INSTAGRAM', 'WHATSAPP'],
    targetAudience: 'Visitantes frequentes da página do evento com alta intenção de compra',
    suggestedBudgetMin: 400,
    suggestedBudgetMax: 1200,
    expectedDurationDays: 3,
    category: 'CONVERSAO',
  },
  {
    id: 'rc-5',
    title: 'Evento nesta Semana',
    slug: 'evento-nesta-semana',
    tagline: 'Contagem Regressiva Final',
    description: 'Anúncios hiper-locais para os indecisos que deixam para comprar na semana do evento.',
    channels: ['GOOGLE_ADS', 'INSTAGRAM', 'WHATSAPP'],
    targetAudience: 'Geolocalização num raio de 40km do local do evento + base local de Curitiba',
    suggestedBudgetMin: 1000,
    suggestedBudgetMax: 3000,
    expectedDurationDays: 5,
    category: 'CONVERSAO',
  },
  {
    id: 'rc-6',
    title: 'Recuperar Carrinhos',
    slug: 'recuperar-carrinhos',
    tagline: 'Resgate de Checkout Abandonado',
    description: 'Disparos automáticos e anúncios de retargeting para quem iniciou o processo de compra.',
    channels: ['WHATSAPP', 'INSTAGRAM', 'EMAIL'],
    targetAudience: 'Usuários com abandono de carrinho registrado nas últimas 48 horas',
    suggestedBudgetMin: 300,
    suggestedBudgetMax: 1000,
    expectedDurationDays: 14,
    category: 'RETENCAO',
  },
  {
    id: 'rc-7',
    title: 'Remarketing de Visitantes',
    slug: 'remarketing-visitantes',
    tagline: 'Reengajamento de Tráfego',
    description: 'Impacto contínuo de quem navegou no evento mas ainda não clicou em Comprar.',
    channels: ['INSTAGRAM', 'GOOGLE_ADS'],
    targetAudience: 'Audiência do Pixel Meta & Google Analytics 4 com visitas nos últimos 30 dias',
    suggestedBudgetMin: 600,
    suggestedBudgetMax: 2000,
    expectedDurationDays: 15,
    category: 'REENGAGEMENT',
  },
  {
    id: 'rc-8',
    title: 'Reativar Compradores',
    slug: 'reativar-compradores',
    tagline: 'Fidelização & Base Histórica',
    description: 'Oferta exclusiva e pré-venda para clientes que já foram a edições anteriores.',
    channels: ['WHATSAPP', 'EMAIL'],
    targetAudience: 'Compradores das edições 2024 e 2025 de eventos da mesma produtora',
    suggestedBudgetMin: 500,
    suggestedBudgetMax: 1800,
    expectedDurationDays: 5,
    category: 'REENGAGEMENT',
  },
];

// Status Real das Campanhas (Vídeo 00:06-00:35)
export const mockAdRealStatus: AdRealStatusItem[] = [
  {
    id: 'ad-01',
    platform: 'META_ADS',
    campaignName: 'Festival XYZ — Meta Conversão Lote 2',
    adSetCount: 3,
    adCount: 8,
    deliveryStatus: 'DELIVERING',
    dailyBudget: 250.0,
    lastSyncAt: 'Há 4 min',
    healthScore: 98,
  },
  {
    id: 'ad-02',
    platform: 'GOOGLE_ADS',
    campaignName: 'Google Search & PMax — Ingressos Festival',
    adSetCount: 2,
    adCount: 6,
    deliveryStatus: 'DELIVERING',
    dailyBudget: 180.0,
    lastSyncAt: 'Há 12 min',
    healthScore: 95,
  },
  {
    id: 'ad-03',
    platform: 'TIKTOK_ADS',
    campaignName: 'TikTok Vídeos Lineup Festival XYZ',
    adSetCount: 2,
    adCount: 4,
    deliveryStatus: 'IN_REVIEW',
    issueDetail: 'Criativo em análise de moderação automática (tempo médio 2h)',
    dailyBudget: 120.0,
    lastSyncAt: 'Há 18 min',
    healthScore: 82,
  },
  {
    id: 'ad-04',
    platform: 'SPOTIFY_ADS',
    campaignName: 'Spotify Audio Ad — Playlist Festival 2026',
    adSetCount: 1,
    adCount: 2,
    deliveryStatus: 'ACTIVE_NO_DELIVERY',
    issueDetail: 'Aguardando validação da CAPI (Conversões de Áudio)',
    dailyBudget: 100.0,
    lastSyncAt: 'Há 25 min',
    healthScore: 70,
  },
  {
    id: 'ad-05',
    platform: 'META_ADS',
    campaignName: 'Meta Criativo 04 — Teste A/B Story',
    adSetCount: 1,
    adCount: 1,
    deliveryStatus: 'REJECTED',
    issueDetail: 'Texto da imagem ultrapassou diretrizes de direitos de imagem de terceiros',
    dailyBudget: 50.0,
    lastSyncAt: 'Há 1h',
    healthScore: 30,
  },
];

// Telemetria Google Analytics 4 (Vídeo 00:59-01:07)
export const mockGa4Events: Ga4EventLog[] = [
  { id: 'ga-1', eventName: 'purchase', timestamp: '14:42:10', userPseudoId: 'usr-889102.1', pageLocation: '/checkout/sucesso', deviceCategory: 'mobile', sourceMedium: 'instagram / cpc', value: 520.0 },
  { id: 'ga-2', eventName: 'begin_checkout', timestamp: '14:38:22', userPseudoId: 'usr-441209.2', pageLocation: '/ingressos/festival-xyz', deviceCategory: 'mobile', sourceMedium: 'google / cpc', value: 260.0 },
  { id: 'ga-3', eventName: 'view_item', timestamp: '14:36:15', userPseudoId: 'usr-190283.4', pageLocation: '/ingressos/festival-xyz', deviceCategory: 'desktop', sourceMedium: 'direct / none' },
  { id: 'ga-4', eventName: 'purchase', timestamp: '14:29:05', userPseudoId: 'usr-552194.8', pageLocation: '/checkout/sucesso', deviceCategory: 'mobile', sourceMedium: 'whatsapp / link', value: 840.0 },
  { id: 'ga-5', eventName: 'page_view', timestamp: '14:25:30', userPseudoId: 'usr-990182.3', pageLocation: '/evento/festival-xyz', deviceCategory: 'mobile', sourceMedium: 'tiktok / video' },
];

// Logs de Transmissão TikTok Events API (Vídeo 01:08-01:17)
export const mockTikTokLogs: TikTokTransmissionLog[] = [
  { id: 'tt-1', timestamp: '14:42:11', eventName: 'CompletePayment', status: 'HTTP_200', latencyMs: 68, pixelId: 'TT-PIXEL-7749', payloadHash: '8f9a2e...10bc' },
  { id: 'tt-2', timestamp: '14:38:23', eventName: 'InitiateCheckout', status: 'HTTP_200', latencyMs: 74, pixelId: 'TT-PIXEL-7749', payloadHash: '4a1b9c...982e' },
  { id: 'tt-3', timestamp: '14:31:02', eventName: 'ViewContent', status: 'HTTP_200', latencyMs: 62, pixelId: 'TT-PIXEL-7749', payloadHash: '1c7e4a...661a' },
  { id: 'tt-4', timestamp: '14:15:40', eventName: 'AddToCart', status: 'HTTP_200', latencyMs: 81, pixelId: 'TT-PIXEL-7749', payloadHash: '9d3f8b...2201' },
];

// Central de Links UTM & Atribuição (Vídeo 01:51-02:05)
export const mockUtmLinks: UtmLinkItem[] = [
  {
    id: 'utm-1',
    eventId: 'ev-101',
    eventName: 'Festival XYZ 2026',
    title: 'Instagram Bio Principal',
    url: 'https://diskingressos.com.br/evento/festival-xyz-2026?utm_source=instagram&utm_medium=bio&utm_campaign=lancamento',
    utmSource: 'instagram',
    utmMedium: 'bio',
    utmCampaign: 'lancamento',
    clicks: 14250,
    visitors: 11800,
    conversions: 680,
    conversionRate: 4.77,
    revenue: 176800.0,
    createdAt: '01/09/2026',
  },
  {
    id: 'utm-2',
    eventId: 'ev-101',
    eventName: 'Festival XYZ 2026',
    title: 'Instagram Stories Anúncios Feed',
    url: 'https://diskingressos.com.br/evento/festival-xyz-2026?utm_source=instagram&utm_medium=stories_paid&utm_campaign=lote2',
    utmSource: 'instagram',
    utmMedium: 'stories_paid',
    utmCampaign: 'lote2',
    clicks: 8420,
    visitors: 6950,
    conversions: 340,
    conversionRate: 4.03,
    revenue: 88400.0,
    createdAt: '15/09/2026',
  },
  {
    id: 'utm-3',
    eventId: 'ev-101',
    eventName: 'Festival XYZ 2026',
    title: 'Google Ads Pesquisa Fundo de Funil',
    url: 'https://diskingressos.com.br/evento/festival-xyz-2026?utm_source=google&utm_medium=cpc&utm_campaign=pesquisa_marca',
    utmSource: 'google',
    utmMedium: 'cpc',
    utmCampaign: 'pesquisa_marca',
    clicks: 5630,
    visitors: 5120,
    conversions: 410,
    conversionRate: 7.28,
    revenue: 106600.0,
    createdAt: '05/09/2026',
  },
  {
    id: 'utm-4',
    eventId: 'ev-101',
    eventName: 'Festival XYZ 2026',
    title: 'TikTok Viral Lineup Revelação',
    url: 'https://diskingressos.com.br/evento/festival-xyz-2026?utm_source=tiktok&utm_medium=video_link&utm_campaign=lineup',
    utmSource: 'tiktok',
    utmMedium: 'video_link',
    utmCampaign: 'lineup',
    clicks: 9800,
    visitors: 7400,
    conversions: 180,
    conversionRate: 1.83,
    revenue: 46800.0,
    createdAt: '10/09/2026',
  },
  {
    id: 'utm-5',
    eventId: 'ev-101',
    eventName: 'Festival XYZ 2026',
    title: 'WhatsApp Disparo Base VIP',
    url: 'https://diskingressos.com.br/evento/festival-xyz-2026?utm_source=whatsapp&utm_medium=broadcast&utm_campaign=pre-venda-vip',
    utmSource: 'whatsapp',
    utmMedium: 'broadcast',
    utmCampaign: 'pre-venda-vip',
    clicks: 3120,
    visitors: 2980,
    conversions: 320,
    conversionRate: 10.25,
    revenue: 83200.0,
    createdAt: '02/09/2026',
  },
];

// Templates WhatsApp Marketing (Vídeo 01:30-01:38)
export const mockWhatsAppTemplates: WhatsAppTemplate[] = [
  {
    id: 'tpl-wa-1',
    name: 'aviso_virada_lote_v1',
    category: 'MARKETING',
    language: 'pt_BR',
    status: 'APPROVED',
    bodyText: 'Olá {{1}}, os ingressos para o {{2}} estão virando de lote em poucas horas! Garanta o seu agora com preço exclusivo de 1º lote pelo link oficial: {{3}}',
    variables: ['Nome do Cliente', 'Nome do Evento', 'Link com UTM'],
  },
  {
    id: 'tpl-wa-2',
    name: 'resgate_carrinho_expira_v2',
    category: 'UTILITY',
    language: 'pt_BR',
    status: 'APPROVED',
    bodyText: 'Ei {{1}}, vimos que você quase garantiu seus ingressos para o {{2}}. Reservamos sua vaga no setor {{3}} por 15 minutos! Finalize seu pedido com segurança: {{4}}',
    variables: ['Nome', 'Evento', 'Setor', 'Link Checkout'],
  },
  {
    id: 'tpl-wa-3',
    name: 'pix_copia_cola_pedido_v1',
    category: 'UTILITY',
    language: 'pt_BR',
    status: 'APPROVED',
    bodyText: 'Olá {{1}}, aqui está seu código PIX para confirmar os ingressos do {{2}}. Valor: R$ {{3}}. Copie o código abaixo e cole no app do seu banco: {{4}}',
    variables: ['Nome', 'Evento', 'Valor', 'Código Pix'],
  },
];

// Templates E-mail Marketing (Vídeo 01:39-01:46)
export const mockEmailTemplates: EmailTemplate[] = [
  {
    id: 'tpl-em-1',
    name: 'Visual Moderno — Virada de Lote 48h',
    subject: '⚠️ Últimas 48 horas de Lote 1 para o {{evento}}',
    previewText: 'O preço vai subir. Garanta seu ingresso com parcelamento em até 12x.',
    category: 'VIRADA_LOTE',
  },
  {
    id: 'tpl-em-2',
    name: 'Alerta de Ingresso Reservado no Carrinho',
    subject: 'Não perca seus ingressos: seu pedido está te esperando!',
    previewText: 'Conclua seu pagamento em 1 clique com PIX ou Cartão.',
    category: 'RECUPERACAO',
  },
  {
    id: 'tpl-em-3',
    name: 'Anúncio de Lineup Oficial e Abertura',
    subject: '💥 Saiu o Lineup Oficial do {{evento}}! Ingressos abertos',
    previewText: 'Confira as atrações confirmadas e reserve seu lugar no melhor setor.',
    category: 'LANCAMENTO',
  },
];

// Automações & Jornadas (Vídeo 01:47-01:50)
export const mockAutomationJourneys: AutomationJourney[] = [
  {
    id: 'jrn-1',
    name: 'Régua de Abandono de Carrinho (15 min)',
    triggerType: 'ABANDONED_CART',
    channel: 'WHATSAPP',
    delayMinutes: 15,
    status: 'ACTIVE',
    executionsCount: 420,
    conversionRate: 28.5,
    recoveredRevenue: 48600.0,
  },
  {
    id: 'jrn-2',
    name: 'E-mail de Segunda Tentativa de Compra (2 horas)',
    triggerType: 'ABANDONED_CART',
    channel: 'EMAIL',
    delayMinutes: 120,
    status: 'ACTIVE',
    executionsCount: 290,
    conversionRate: 14.2,
    recoveredRevenue: 19800.0,
  },
  {
    id: 'jrn-3',
    name: 'Alerta Antecipado de Virada de Lote (T-24h)',
    triggerType: 'LOT_CHANGE',
    channel: 'MULTICHANNEL',
    delayMinutes: 0,
    status: 'ACTIVE',
    executionsCount: 1540,
    conversionRate: 9.8,
    recoveredRevenue: 64200.0,
  },
];

// Oportunidades do WhatsApp Remarketing — A TELA DO VÍDEO (02:24-02:34)
export const mockRecoveryOpportunities: RecoveryOpportunity[] = [
  {
    id: 'rec-01',
    customerName: 'Mariana Duarte Souza',
    customerPhone: '(41) 99881-2233',
    customerEmail: 'mariana.duarte@gmail.com',
    eventId: 'ev-101',
    eventName: 'Festival XYZ 2026',
    utmSource: 'instagram_stories',
    utmCampaign: 'lote2_press',
    itemsDescription: '2x Pista Premium VIP',
    ticketCount: 2,
    cartValue: 520.0,
    timeAgo: 'há 14 min',
    abandonedAt: '2026-10-09T14:41:00',
    status: 'ABERTO',
    channel: 'WHATSAPP',
    pixKey: '00020126580014br.gov.bcb.pix0136d8f89...5204000053039865405520.005802BR5913DiskIngressos',
  },
  {
    id: 'rec-02',
    customerName: 'Lucas Eduardo Silveira',
    customerPhone: '(41) 98711-4455',
    customerEmail: 'lucas.silveira@outlook.com',
    eventId: 'ev-101',
    eventName: 'Festival XYZ 2026',
    utmSource: 'google_cpc',
    utmCampaign: 'pesquisa_marca',
    itemsDescription: '1x Camarote Open Bar',
    ticketCount: 1,
    cartValue: 420.0,
    timeAgo: 'há 28 min',
    abandonedAt: '2026-10-09T14:27:00',
    status: 'ABERTO',
    channel: 'WHATSAPP',
    pixKey: '00020126580014br.gov.bcb.pix0136ab129...5204000053039865405420.005802BR5913DiskIngressos',
  },
  {
    id: 'rec-03',
    customerName: 'Beatriz Vasconcelos',
    customerPhone: '(41) 99234-8899',
    customerEmail: 'b.vasconcelos@uol.com.br',
    eventId: 'ev-101',
    eventName: 'Festival XYZ 2026',
    utmSource: 'tiktok_video',
    utmCampaign: 'lineup_viral',
    itemsDescription: '4x Pista Geral',
    ticketCount: 4,
    cartValue: 600.0,
    timeAgo: 'há 45 min',
    abandonedAt: '2026-10-09T14:10:00',
    status: 'EM_RESGATE',
    channel: 'WHATSAPP',
    pixKey: '00020126580014br.gov.bcb.pix0136cc881...5204000053039865405600.005802BR5913DiskIngressos',
    lastActionNote: 'Disparo de WhatsApp enviado às 14:15',
    dispatchedAt: '2026-10-09T14:15:00',
  },
  {
    id: 'rec-04',
    customerName: 'Guilherme Augusto Ramos',
    customerPhone: '(41) 98455-1122',
    customerEmail: 'guilherme.ramos@empresa.com.br',
    eventId: 'ev-102',
    eventName: 'Show Nacional ABC 2026',
    utmSource: 'instagram_bio',
    utmCampaign: 'abertura_geral',
    itemsDescription: '2x Pista Padrão',
    ticketCount: 2,
    cartValue: 310.0,
    timeAgo: 'há 1h 12m',
    abandonedAt: '2026-10-09T13:43:00',
    status: 'RECUPERADO',
    channel: 'WHATSAPP',
    pixKey: '00020126580014br.gov.bcb.pix0136ee991...5204000053039865405310.005802BR5913DiskIngressos',
    verifiedTransactionId: 'TX-PIX-908124',
    lastActionNote: 'Venda confirmada via PIX às 14:02',
  },
  {
    id: 'rec-05',
    customerName: 'Camila Fernandes Lopes',
    customerPhone: '(41) 99677-3344',
    customerEmail: 'camila.lopes@gmail.com',
    eventId: 'ev-101',
    eventName: 'Festival XYZ 2026',
    utmSource: 'whatsapp_broadcast',
    utmCampaign: 'vip_lote1',
    itemsDescription: '2x Camarote Open Bar',
    ticketCount: 2,
    cartValue: 840.0,
    timeAgo: 'há 1h 45m',
    abandonedAt: '2026-10-09T13:10:00',
    status: 'EM_RESGATE',
    channel: 'WHATSAPP',
    pixKey: '00020126580014br.gov.bcb.pix0136ff442...5204000053039865405840.005802BR5913DiskIngressos',
    lastActionNote: 'Link de resgate aberto pelo cliente',
  },
];

